#ifndef NUM_REPLIES_HPP
#define NUM_REPLIES_HPP

#define NO_ERR 000

#define RPL_BOUNCE 005

#define RPL_NAMEREPLY 353
#define RPL_ENDOFNAMES 366

#define ERR_NOSUCHNICK 401
#define ERR_NOSUCHCHANNEL 403
#define ERR_USERNOTINCHANNEL 441
#define ERR_NOTONCHANNEL 442
#define ERR_USERONCHANNEL 443

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NICKCOLISSION 436

#define ERR_PASSWDMISMATCH 464
#define ERR_BADCHANNELKEY 475
#define ERR_CHANOPRIVSNEEDED 482

#endif
